import React from 'react'

function page() {
  return (
    <div>
      <h1>Photo Gallery</h1>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque, dignissimos maiores officia in atque corrupti recusandae labore maxime quibusdam, molestias illum! Quasi odio explicabo nesciunt veritatis sed tenetur, soluta eligendi est quod provident ipsa corrupti, dicta, minima nobis voluptatum minus dolorum. Atque nam quae tempora esse illum delectus perspiciatis voluptate sint culpa, excepturi blanditiis cumque iste eligendi aut eos deserunt. Nulla ut numquam id at sint nobis rerum ex reiciendis labore, deleniti, blanditiis debitis dignissimos illum eaque maxime iure. Ducimus enim labore vero esse laboriosam quia iure omnis maxime veritatis repellat. Nostrum assumenda alias quos deserunt voluptatibus, veritatis culpa, porro, unde fuga nemo blanditiis accusantium explicabo quibusdam exercitationem vel laboriosam ipsum incidunt optio eaque. Harum, dolorum. Eligendi tempore ducimus temporibus ad laboriosam non dolorem natus praesentium saepe id beatae quas, odio, provident aliquam facilis. Iusto dignissimos consequatur dolores aliquam ex reprehenderit, veritatis voluptatem, rerum consequuntur tempore aperiam illum quod quos est, non at aspernatur commodi neque? Quo culpa placeat rerum, eligendi, porro pariatur labore necessitatibus doloremque exercitationem beatae perferendis vel nostrum debitis recusandae facilis ipsa magnam impedit. Aut dignissimos odit minus? Rem voluptas sapiente quae, corporis molestias alias ipsum dolor repudiandae fugiat, voluptatum possimus neque natus voluptates dolorem voluptate architecto?
      <br/>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, ducimus veritatis nemo libero adipisci sequi soluta maiores velit corporis quo ipsa rerum mollitia doloremque cum saepe ab consequatur nisi quisquam, facere ex eos ratione. Fugit quis accusamus quia assumenda possimus, aperiam vel ipsa molestias nam ipsam, et officiis sequi, tenetur id molestiae esse. Odit, officiis porro. Dolorem nostrum odio possimus expedita libero ea perferendis asperiores vero nisi eos exercitationem ducimus aliquam illo reprehenderit repellat aut voluptas, quos ad eius. Consectetur molestiae commodi dolorum, quis tempora illo exercitationem, corrupti praesentium consequuntur asperiores, illum eum! Qui quidem placeat tempora sed quae animi dolorem dolores maiores pariatur a, reiciendis nostrum, at eaque. Quae maiores omnis reprehenderit similique odit dolore perspiciatis, iure autem pariatur? Architecto et aperiam corporis! Hic vitae modi nisi eum ipsam labore tempora dicta, dolor minus explicabo odit nesciunt saepe ut eos ab corrupti nam totam at assumenda dolorem est dolore error. Optio rerum exercitationem quia vel, eligendi incidunt similique unde! Suscipit dignissimos placeat, temporibus dicta, veritatis accusantium illum rem vero dolorem perferendis minus animi error aperiam repudiandae esse consequuntur tenetur sint est aliquam quis ducimus saepe. Hic iusto quasi excepturi at perspiciatis consequuntur itaque? Officiis saepe nostrum consectetur quod, enim ut corporis culpa facilis et. A accusamus aspernatur sapiente autem alias nobis sequi. Quae laboriosam doloribus totam quos repudiandae vitae quasi voluptatibus reiciendis debitis soluta autem deserunt quaerat impedit illum facilis natus veniam provident, modi accusamus sit consequatur ut culpa iste? Omnis, labore! Vel delectus in magnam. Dignissimos architecto, dicta provident asperiores minus omnis nam ratione vitae voluptatibus ex fugit eligendi suscipit modi dolor possimus doloremque tempora? Laboriosam dicta, non corporis similique repellendus fugiat nostrum? Ducimus quod, consectetur eligendi corrupti neque enim itaque vitae explicabo tempore magnam ea perferendis aperiam eos deserunt numquam delectus libero inventore iste error quibusdam? Mollitia.</div>
  )
}

export default page